name: jsonplaceholder_example
description: JSON Placeholder Example App
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_data:
    path: ../../flutter_data
  json_annotation: ^3.0.1
  riverpod: ^0.6.1
  get_it: ^4.0.2

dev_dependencies:
  build_runner:
  json_serializable: ^3.2.5