name: flutter_data
description: >
  A pragmatic tool to build data-driven Flutter apps
  with minimal boilerplate, based on the Active Record pattern.
version: 0.1.1
homepage: https://github.com/flutterdata/flutter_data
documentation: https://flutterdata.dev/docs
authors:
  - Frank Treacy <me@frank06.net>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  source_gen: ^0.9.0
  uuid: ^2.0.4
  http: ^0.12.0+2
  inflection2: ^0.4.3
  hive: ^1.3.0
  path: ^1.6.4
  equatable: ^1.1.0
  json_api: ^3.2.3
  recase: ^3.0.0
  data_state:
    git:
      url: git://github.com/flutterdata/data_state.git
      ref: 0.2.0
  debounce_throttle: ^1.1.0
  rxdart: ^0.23.1

dev_dependencies:
  test: ^1.9.4
  mockito: ^4.1.1
  analyzer: ^0.39.2+1
  pedantic: ^1.8.0+1
  freezed: ^0.10.4
  freezed_annotation: ^0.7.1

  build_test: ^0.10.11
  build_runner: ^1.7.4
  matcher: ^0.12.6
  source_gen_test: ^0.1.0
  json_serializable: ^3.2.5
  json_annotation: ^3.0.1