name: flutter_data
description: >
  Flutter Data is a library for seamlessly managing persistent data in Flutter apps
version: 0.3.12
homepage: https://github.com/flutterdata/flutter_data
documentation: https://flutterdata.dev/

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  uuid: ^2.0.4
  inflection2: ^0.4.3
  path: ^1.6.4
  json_api: ^4.2.1
  data_state: ">= 0.2.5 < 1.0.0"
  async: ^2.4.0
  meta: ^1.1.8
  rxdart: ">= 0.23.1 < 1.0.0"
  http: ^0.12.0+4
  hive: ^1.4.1+1
  analyzer: ^0.39.7
  source_gen: ^0.9.5
  pubspec_parse: ^0.1.5
  glob: ^1.2.0
  build: ^1.2.2

dev_dependencies:
  test: ^1.9.4
  mockito: ^4.1.1
  
  pedantic: ^1.8.0+1
  freezed: ^0.10.8
  freezed_annotation: ^0.7.1

  build_test: ^0.10.11
  build_runner: ^1.7.4
  matcher: ^0.12.6
  source_gen_test: ^0.1.0
  json_serializable: ^3.2.5
  json_annotation: ^3.0.1