name: flutter_data
description: >
  The seamless way to work with persistent data models in Flutter.
  Inspired by Ember Data and ActiveRecord.
version: 0.5.3
homepage: https://github.com/flutterdata/flutter_data
documentation: https://flutterdata.dev/

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  uuid: ^2.0.4
  inflection2: ^0.4.3
  path: ^1.6.4
  data_state: ^0.3.5
  async: ^2.4.0
  meta: ^1.1.8
  http: ^0.12.0+4
  hive: ^1.4.1+1
  riverpod: ^0.10.0
  state_notifier: ">= 0.6.0 <1.0.0"
  
  # codegen
  build: ^1.3.0
  analyzer: ^0.39.14
  source_gen: ^0.9.5
  pubspec_parse: ^0.1.5
  glob: ^1.2.0
  # require fixed build_resolvers
  build_resolvers: ">= 1.3.10 <1.4.0"

dev_dependencies:
  test: ^1.9.4
  mockito: ^4.1.1
  pedantic: ^1.8.0+1
  build_test: ^0.10.11
  build_runner: ^1.10.0
  matcher: ^0.12.6
  source_gen_test: ^0.1.0
  json_serializable: ^3.2.5
  json_annotation: ^3.0.1
  freezed: ^0.11.4
  freezed_annotation: ^0.11.0
  test_coverage: ^0.4.3